### ISSUE TITLE
该项目在本地用 phpStudy   Nginx+PHP7.x+MySQL^5.5无法访问，会一直跳转在首页

### ISSUE THREAD

**Issue by klzdy123** [loveyu/StudentManage#2]
![image](https://user-images.githubusercontent.com/24836285/77248448-5669c580-6c74-11ea-9778-4eeeebf41c6a.png)

**Comment by klzdy123** [comment]
在Linux上可以正常运行的

**Comment by loveyu** [comment]
> 在Linux上可以正常运行的

应该是伪静态规则的问题，目前没最phpStudy进行过兼容

**Comment by klzdy123** [comment]
谢谢回信。在部署时已经对nginx进行了伪静态，将项目的Nginx配置文件负责到配置文件的server中，但是还是会一直刷新，URL越来越长。好在切换到apache后能正常访问



---原始邮件---
发件人: "loveyu"<notifications@github.com&gt;
发送时间: 2020年3月22日(周日) 晚上7:43
收件人: "loveyu/StudentManage"<StudentManage@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"klzdy123"<1009927694@qq.com&gt;;
主题: Re: [loveyu/StudentManage] 该项目在本地用 phpStudy   Nginx+PHP7.x+MySQL^5.5无法访问，会一直跳转在首页 (#2)




  
在Linux上可以正常运行的
  
应该是伪静态规则的问题，目前没最phpStudy进行过兼容
